version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
